### ISSUE TITLE
Nallatech and Alpha-data card have different offsets for vsec

### ISSUE THREAD

**Issue by kenhill** [mbrobbel/capi-flash-script#2]
It turns out there is a different offset for the Alpha-data and Nallatech cards when using setpci (error occurs when the Nallatech psl-revision is not 0000). It is safer to use psl_revision from sysfs. 

For master, this would change line 52 from:
 p[$i]=`setpci -s ${d:0:12} 40C.W`;
to:
 p[$i]=$(cat /sys/class/cxl/card$i/psl_revision | xargs printf "%.4X");

**Comment by mbrobbel** [comment]
Please refer to #3.
