### ISSUE TITLE
Script shows from card type

### ISSUE THREAD

**Issue by fhaverkamp** [mbrobbel/capi-flash-script#3]
Hi,

I used a previous version of this script to update my Nallatech cards and it showed the card version correctly:
$ sudo /usr/local/bin/capi-flash-script.sh ../../cgzip.603_0.20160316.r844-000_debug_

Current date:
Wed Mar 23 15:20:15 CET 2016
# Card                           Flashed                       by                   Image

card0   Nallatech Altera               Fri Mar 18 15:41:37 CET 2016  haver                cgzip.603_0.20160316.r844-000_debug_basic.rbf
card1   Nallatech Altera               Fri Mar 18 14:30:37 CET 2016  haver                cgzip.603_0.20160316.r844-000_debug_basic.rbf

After I tried to update the script to the latest version it comes with this:

haver@tul2eth3:~/HTX/capi-flash-script$ sudo ./capi-flash-script.sh ../../cgzip.603_0.20160316.r844-000_debug_basic.rbf 

Current date:
Wed Mar 23 15:18:28 CET 2016
# Card                           Flashed                       by                   Image

card0   Convey Xilinx                  Fri Mar 18 15:41:37 CET 2016  haver                cgzip.603_0.20160316.r844-000_debug_basic.rbf
card1   Convey Xilinx                  Fri Mar 18 14:30:37 CET 2016  haver                cgzip.603_0.20160316.r844-000_debug_basic.rbf

No, this is a Nallatech card and not a Xilinx ... Something must have changed to mess this up.
Can this be fixed somehow?

Regards

Frank

**Comment by mbrobbel** [comment]
Hi Frank,

Thank you for reporting this. It must be related to #2.
I'm currently no longer actively developing or using this script so I'll revert that fix and reopen the issue to let the author figure out what went wrong.

Best regards

**Comment by kenhill** [comment]
Hi Frank,

I believe this is an issue with the psl-revision file. Are you using a new psl version for the Nallatech card? You can check this with: cat /sys/class/cxl/cardX/psl_revision  where X is the card number.

The new Nallatech psl that I'm aware of is 0001, whereas the Convey psl version should be 1001. 

I can update the project after you confirm the revision number. 

Thanks
